version: '3.7'

services:
  hmis-node-server:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
    container_name: hmis-node-server
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: yarn dev
