export { default as authRouter } from 'modules/auth/router'
export * from 'modules/auth/socket'
export * from 'modules/auth/models/user'
export * from 'modules/auth/middlewares/auth'
export * from 'modules/auth/setup'
